// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVphBKTGzUPniT4DM0uQWcGTLgbrhBcaY',
    appId: '1:1047947161236:web:0ce09344e5aa574f344e81',
    messagingSenderId: '1047947161236',
    projectId: 'zezo-10aad',
    authDomain: 'zezo-10aad.firebaseapp.com',
    storageBucket: 'zezo-10aad.firebasestorage.app',
    measurementId: 'G-EQ0ESTSTEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPqGGaz6ro9nnuVgI9k13Ca3e04ECASN4',
    appId: '1:1047947161236:android:bebdfb66b6c4c9e6344e81',
    messagingSenderId: '1047947161236',
    projectId: 'zezo-10aad',
    storageBucket: 'zezo-10aad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY5INtWdIojbAkBrR4eHHlUgudROho5TQ',
    appId: '1:1047947161236:ios:60c12fbd329c99c8344e81',
    messagingSenderId: '1047947161236',
    projectId: 'zezo-10aad',
    storageBucket: 'zezo-10aad.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY5INtWdIojbAkBrR4eHHlUgudROho5TQ',
    appId: '1:1047947161236:ios:60c12fbd329c99c8344e81',
    messagingSenderId: '1047947161236',
    projectId: 'zezo-10aad',
    storageBucket: 'zezo-10aad.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB701uAfKGAgDAk6qMuPC5xtJyTAV7pRV4',
    appId: '1:1047947161236:web:2fd42e3c50d13c26344e81',
    messagingSenderId: '1047947161236',
    projectId: 'zezo-10aad',
    authDomain: 'zezo-10aad.firebaseapp.com',
    storageBucket: 'zezo-10aad.firebasestorage.app',
    measurementId: 'G-3FWDL9VGD7',
  );
}
